In [ ]:
import joblib
import numpy as np

# Load model
svm_model = joblib.load('model_Svm_sirosis.pkl')



In [2]:
# Load scaler yang telah disimpan
scaler = joblib.load('scaler_sirosis.pkl')

In [ ]:
# import numpy as np

# # Input data untuk prediksi
# # Input data untuk prediksi
# features = np.array([
#     1504,   # N_Days
#     1,     # Drug
#     13918,    # Age
#     1,     # Sex
#     0,     # Ascites
#     1,     # Hepatomegaly
#     0,     # Spiders
#     1,     # Edema
#     1.2,   # Bilirubin
#     279,   # Cholesterol
#     3.53,   # Albumin
#     143,   # Copper
#     671,    # Alk_Phos
#     113.15,    # SGOT
#     72,   # Tryglicerides
#     136,   # Platelets
#     10.9,    # Prothrombin
#     3      # Stage
# ]).reshape(1, -1)  # Bentuk array menjadi 2D

# # Prediksi
# prediction = model.predict(features)
# print(f"Hasil prediksi Status: {prediction[0]}")



In [21]:
import numpy as np

# Input data untuk prediksi dari dataset
feature_sets = [
    np.array([1504, 1, 13634, 0, 0, 1, 1, 0, 3.4, 279, 3.53, 143, 671, 113.15, 72, 136, 10.9, 3]),  # ID 5
    np.array([2503, 1, 24201, 0, 0, 1, 0, 0, 0.8, 248, 3.98, 50, 944, 93.00, 63, 257, 11.0, 3]),   # ID 6
    np.array([3762, 1, 19619, 0, 0, 1, 1, 0, 1.4, 259, 4.16, 46, 1104, 79.05, 79, 258, 12.0, 4]),  # ID 11
    np.array([3577, 1, 16688, 0, 0, 0, 0, 0, 0.7, 281, 3.85, 40, 1181, 88.35, 130, 244, 10.6, 3]),  # ID 13
    np.array([3672, 1, 14772, 0, 0, 0, 0, 0, 0.7, 204, 3.66, 28, 685, 72.85, 58, 198, 10.8, 3])    # ID 16
]

# Ubah list feature_sets menjadi array 2D
feature_sets = np.array(feature_sets)

# Variabel untuk menyimpan true_labels
true_labels = []

# Prediksi untuk setiap set fitur
for i, features in enumerate(feature_sets):
    # Lakukan scaling pada data baru
    scaled_features = scaler.transform(features.reshape(1, -1))  # Ubah fitur menjadi bentuk 2D (1 sample, n features)
    
    # Prediksi menggunakan model
    prediction = svm_model.predict(scaled_features)
    
    # Tambahkan hasil prediksi ke dalam true_labels
    true_labels.append(prediction[0])
    
    # Cetak hasil prediksi
    print(f"Hasil prediksi Status untuk ID {i + 1}: {prediction[0]}")

Hasil prediksi Status untuk ID 1: 1
Hasil prediksi Status untuk ID 2: 2
Hasil prediksi Status untuk ID 3: 2
Hasil prediksi Status untuk ID 4: 0
Hasil prediksi Status untuk ID 5: 0


C:\Users\jstwy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\jstwy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\jstwy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\jstwy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:465: UserWarning:

In [ ]:
# # Meminta input dari pengguna
# n_days = int(input("Masukkan jumlah hari sejak diagnosis (N_Days): "))
# drug = int(input("Masukkan nama obat yang sedang dikonsumsi: "))
# age = int(input("Masukkan usia pasien: "))
# sex = int(input("Masukkan jenis kelamin (1=Pria, 0=Wanita): "))
# ascites = int(input("Apakah pasien memiliki ascites (1=Ya, 0=Tidak): "))
# hepatomegaly = int(input("Apakah pasien memiliki hepatomegaly (1=Ya, 0=Tidak): "))
# spiders = int(input("Apakah pasien memiliki spiders (1=Ya, 0=Tidak): "))
# edema = int(input("Apakah pasien memiliki edema (1=Ya, 0=Tidak): "))
# bilirubin = float(input("Masukkan nilai bilirubin (mg/dL): "))
# cholesterol = float(input("Masukkan nilai kolesterol (mg/dL): "))
# albumin = float(input("Masukkan nilai albumin (g/dL): "))
# copper = float(input("Masukkan nilai tembaga (µg/dL): "))
# alk_phos = float(input("Masukkan nilai alkaline phosphatase (IU/L): "))
# sgot = float(input("Masukkan nilai SGOT (IU/L): "))
# tryglicerides = float(input("Masukkan nilai trigliserida (mg/dL): "))
# platelets = float(input("Masukkan jumlah trombosit (10^3/µL): "))
# prothrombin = float(input("Masukkan waktu prothrombin (detik): "))
# stage = int(input("Masukkan stadium penyakit (1-4): "))

# # Gabungkan input menjadi array numpy
# features = np.array([
#     n_days, drug, age, sex, ascites, hepatomegaly, spiders, edema,
#     bilirubin, cholesterol, albumin, copper, alk_phos, sgot,
#     tryglicerides, platelets, prothrombin, stage
# ]).reshape(1, -1)

# # Normalisasi data dengan scaler
# scaled_features = scaler.transform(features)

# # Prediksi menggunakan model
# prediction = svm_model.predict(scaled_features)

# # Cetak hasil prediksi
# print(f"Hasil prediksi Status: {prediction[0]}")


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Melakukan scaling pada data input (menggunakan fitur yang sudah diubah menjadi 2D)
scaled_input_data = scaler.transform(feature_sets)

# Prediksi untuk setiap input
predictions = svm_model.predict(scaled_input_data)


Akurasi untuk input pengguna: 100.00%


C:\Users\jstwy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:


# Cetak hasil prediksi untuk setiap ID
for i, prediction in enumerate(predictions):
    print(f"Hasil prediksi Status untuk ID {i + 1}: {prediction}")

# Menghitung akurasi
accuracy = accuracy_score(true_labels, predictions)
print(f"\nAkurasi untuk input pengguna: {accuracy * 100:.2f}%")

# Evaluasi lebih lanjut: confusion matrix dan classification report
conf_matrix = confusion_matrix(true_labels, predictions)
class_report = classification_report(true_labels, predictions)

print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

Hasil prediksi Status untuk ID 1: 1
Hasil prediksi Status untuk ID 2: 2
Hasil prediksi Status untuk ID 3: 2
Hasil prediksi Status untuk ID 4: 0
Hasil prediksi Status untuk ID 5: 0

Akurasi untuk input pengguna: 100.00%

Confusion Matrix:
[[2 0 0]
 [0 1 0]
 [0 0 2]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         2

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

